### ISSUE TITLE
Passing initializationParams

### ISSUE THREAD

**Issue by ChrisChinchilla** [errata-ai/vale-ls#16]
I am not sure if this is a vale-ls question or a VSCode question, but I've been looking back and forth in code here, the Sublime extension, and other LSP extensions, and I am completely stuck on how to pass the `initializationParams` to the server. How does vale-ls expect them? Can they be something like `--configPath=xxx` or something else?

I am really struggling to find any examples, at least in the VSCode extension space, that suit the way the parameters are presented in https://vale.sh/docs/integrations/guide/#vale-ls, so if anyone has any ideas, that would be great!

**Comment by jdkato** [comment]
It should be something like this:

```js
let clientOptions: LanguageClientOptions = {
    // ...
    initializationOptions: myOptions,
};
```
where `myOptions` is a `Record<string, any>`.

**Comment by ChrisChinchilla** [comment]
Yup, this is working, thanks!
