### ISSUE TITLE
installVale to where?

### ISSUE THREAD

**Issue by ChrisChinchilla** [errata-ai/vale-ls#18]
It's possible to set `installVale` to true and install vale… Where does it install to? Where from? The latest version?

**Comment by jdkato** [comment]
It installs the latest version to the location of the `vale-ls` executable.

**Comment by jdkato** [comment]
It will also auto-update to the latest version.

**Comment by ChrisChinchilla** [comment]
@jdkato Yup, I went to my git history and suddenly noticed that I will make  PRs to add details.
