### ISSUE TITLE
vale-ls doesn't work on Windows (fix included)

### ISSUE THREAD

**Issue by veksha** [errata-ai/vale-ls#9]
`uri.path()` will return `/C:/file.txt` on windows and call to vale.exe will fail.
`uri.path()` is returning uri component called "path" (not what we want), i think it's better to use `uri.to_file_path()` to get file path in correct format.

```diff
diff --git a/src/server.rs b/src/server.rs
index c84f874..a3242c0 100644
--- a/src/server.rs
+++ b/src/server.rs
@@ -380,7 +380,7 @@ impl Backend {
 
         self.update(params.clone());
         if self.cli.is_installed() {
-            match self.cli.run(uri.path(), self.config_path(), self.config_filter()) {
+            match self.cli.run(uri.to_file_path().unwrap().to_str().unwrap(), self.config_path(), self.config_filter()) {
                 Ok(result) => {
                     let mut diagnostics = Vec::new();
                     for (_, v) in result.iter() {

```

**Comment by veksha** [comment]
and i think it will solve https://github.com/errata-ai/vale-ls/issues/6 issue too.

**Comment by veksha** [comment]
also `to_file_path` should be checked for errors, it can fail on urls like `file:///Untitled1`.

**Comment by jdkato** [comment]
Thanks for looking into this.

I can confirm that it fixes #6, but I can't test on Windows at the moment.

**Comment by veksha** [comment]
@jdkato, tested your commit on Windows. works fine.
for new tabs which were not yet saved to files it outputs `File path error: Some(())`, but continues to work for other tabs.

**Comment by jdkato** [comment]
I'll make the log message more clear in the next release.
